### ISSUE TITLE
Link incidents to corresponding TMC

### ISSUE THREAD

**Issue by dolejarz** [CityofToronto/bdit_incidents#6]

**Comment by radumas** [comment]
- [x] ensure checking for incident & TMC direction (note peculiarities of TMC directions...)
- [x] Use PostGIS's K-Nearest Neighbour search [like this?](http://gis.stackexchange.com/a/136416/36886)

**Comment by radumas** [comment]
Rough PostgreSQL outline

```sql
CREATE OR REPLACE FUNCTION match_tmc(point GEOMETRY, OUT tmc char(9), OUT tmc_distance float)
```

And then usage like (may not work)
```SELECT (match_tmc(point)).*, (match_tmc(point)).tmc, (match_tmc(point)).tmc_distance
FROM incidents``` 

Or [like this](http://gis.stackexchange.com/a/144230/36886)
